language: objective-c
osx_image: xcode8.3
before_install:
  - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get stable

install:
  - gem install xcpretty

script: travis_retry xcodebuild -project BlahApp.xcodeproj -scheme BlahApp -destination "platform=iOS Simulator,name=iPhone SE,OS=10.2"  test CODE_SIGNING_REQUIRED=NO | xcpretty -c
