language: objective-c
osx_image: xcode8.3

script: travis_retry xcodebuild clean test -project BlahApp.xcodeproj -scheme BlahApp -destination "platform=iOS Simulator,name=iPhone SE,OS=10.2" CODE_SIGNING_REQUIRED=NO | xcpretty -c
